name: 'prasant'
description: 'Say "Thank You" to new pull requests'
author: 'prasant'

inputs:
  html_file:
    description: 'The HTML file you want to preview, relative to the root of the repo'
    required: true
    default: 'dist/xyz.html'

  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  TENOR_TOKEN:
    description: 'Tenor API token'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'